module.exports = {
  testEnvironment: 'jsdom',
  transform: {
    '^.+\\.[jt]sx?$': 'babel-jest',
  },
  moduleNameMapper: {
    '\\.(css|less|scss|sass)$': '<rootDir>/__mocks__/styleMock.js',
    '@todo-app/shared': '<rootDir>/../shared/src/index.js',
  },
  setupFilesAfterEach: undefined,
  setupFilesAfterFramework: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterEach: undefined,
  setupFilesAfterFramework: undefined,
  setupFilesAfterEach: undefined,
};
